"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";
import { ChevronRight, Droplet, Droplets } from "lucide-react";
import { useWeb3Modal } from "@web3modal/react";
import { Button } from "@/components/ui/button";
import { useAccount } from "wagmi";
import { disconnect } from "@wagmi/core";
import { usePathname } from "next/navigation";
import { ThemeProvider } from "@/components/theme-provider";
import LensProvider from "./lens-provider";
import { WalletProvider } from "./WalletProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function AppWithProviders({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Nav />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

function Nav() {
  const { open, close } = useWeb3Modal();
  const { address } = useAccount();

  return (
    <nav>
      <div>
        <Link href="/" className="">
          <Droplets />
        </Link>
      </div>
    </nav>
  );
}

export default function RootLayout({ children, ...props }) {
  return (
    <LensProvider>
      <AppWithProviders>
        <WalletProvider>{children}</WalletProvider>
      </AppWithProviders>
    </LensProvider>

    // <html lang="en">
    //   <body className={inter.className}>{children}</body>
    // </html>
  );
}
